_GCP_PROJECT_ID: "The GCP project ID where the resources are located"
_GCS_BUCKET_NAME_MODELS: "The GCS bucket name where the models will be saved"
_TOPIC_TRAINING_COMPLETE: "The Pub/Sub topic name where the success message will be published"
