_GCP_PROJECT_ID: "The GCP project ID where the resources are located"
_BIGQUERY_DATASET_ID: "The BigQuery dataset ID you created"
_BIGQUERY_FACTS_TABLE_ID: "The BigQuery staging table ID"
_BIGQUERY_STAGING_TABLE_ID: "The BigQuery facts table ID where the data will be moved towards"
_TOPIC_UPDATE_FACTS_COMPLETE: "The Pub/Sub topic ID where you will send a message once the data is ingested"
