_GCP_PROJECT_ID: "The GCP project ID where the resources are located"
_BIGQUERY_DATASET_ID: "The BigQuery dataset ID you created"
_BIGQUERY_TABLE_ID: "The BigQuery table ID where you will store the data"
_TOPIC_INGESTION_COMPLETE: "The Pub/Sub topic ID where you will send a message once the data is ingested"
